emergencyRoomMain.c: linked_list_hospital.c patient.c

patient.c: patient.h

linked_list_hospital.c: linked_list_hospital.h

er.out: emergencyRoomMain.o linked_list_hospital.o patient.o

clean:
	rm -f *.o er.out
